FROM debian:trixie

RUN apt-get update && apt-get install -y \
	npm nodejs python3 curl git ripgrep fd-find && \
	rm -rf /var/lib/apt/lists/*

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="$PATH:/root/.local/bin"

RUN curl -fsSL https://pi.dev/install.sh | sh
